#pragma config(Sensor, in1,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in2,    driveGyro,      sensorGyro)
#pragma config(Sensor, dgtl1,  liftUpperEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  groundLiftBump, sensorTouch)
#pragma config(Sensor, dgtl5,  driveEncoderRB, sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  liftUpperEncoder2, sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  portabaseBump,  sensorTouch)
#pragma config(Sensor, dgtl11, liftLowerEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           driveLFT,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           driveLFBB,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           portaBaseR,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           portaBaseL,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           liftT,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           liftB,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           armR,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           driveRFBB,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          driveRFT,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Declarations.c"
#include "RandomFuncts.c"
#include "InputOutput.c"
#include "DriveControl.c"
#include "AutoStructs.c"
#include "AutoRouts.c"
#include "LCD.c"

task main () {
	while (true) {
		clearTimer(T2);
		getInput();
		lcd();
		if (bIfiRobotDisabled) { // If the robot is disabled, run the disabled LCD mode
			lcdDisabled();
		} else if (bIfiAutonomousMode) { // If it's in auto. mode, run autonomous LCD
			lcdAutonomous();
			if (!autoIsDone) { // And if the autonomous isn't done, run autonomous control
				autonomousControl();
			}
		} else { // If it's neither of those modes, run driver LCD and driver control
			wasDisabled = false;
			driverControl();
			lcdDriver();
		}
		doOutput(); // Then do output
		sleep(1);
	}
}
